### ISSUE TITLE
new uninitialised constant error in latest code

### ISSUE THREAD

**Issue by ikbenben** [benedikt/layer-ruby#10]
Hi Benedikt,

I'm getting a new error after updating to the latest code. I had first updated my gemfile to point to 0.5 instead of the master branch after which i encountered this issue. I then reverted my gemfile back to point to master and was still getting this error

    NameError: uninitialized constant Layer::Exceptions::Exceptions
        from /usr/local/bundle/bundler/gems/layer-ruby-4e977da41d83/lib/layer/client.rb:79:in `rescue in request'
        from /usr/local/bundle/bundler/gems/layer-ruby-4e977da41d83/lib/layer/client.rb:66:in `request'
        from /usr/local/bundle/bundler/gems/layer-ruby-4e977da41d83/lib/layer/client/platform.rb:18:in `request'
        from /usr/local/bundle/bundler/gems/layer-ruby-4e977da41d83/lib/layer/client.rb:38:in `post'
        from /usr/local/bundle/bundler/gems/layer-ruby-4e977da41d83/lib/layer/operations/create.rb:13:in `create'
        from /fitmo/app/services/messaging/message_service.rb:25:in `get_conversation'

how to reproduce this issue is to create a distinct conversation without any metadata. afterwards try to create the same conversation but this time with meta data. It should fail because distinct conversations need to be unique. 

Before I modified the Gemfile, i.e. before I updated to the latest code, I got a meaningful "Layer::Exceptions::Conflict:" exception. 

cheers

**Comment by benedikt** [comment]
Hi @ikbenben,

thanks for reporting this. I'm not sure how this could slip into the code without being noticed. I just fixed the issue on the master branch. Can you verify that this doesn't happen anymore? 

Cheers,

Benedikt

**Comment by ikbenben** [comment]
Hi @benedikt . it appears to be resolved. cheers
