### ISSUE TITLE
How to get messages in a conversation

### ISSUE THREAD

**Issue by ikbenben** [benedikt/layer-ruby#13]
Hi @benedikt 

I'm back and trying to work on a migration script to move messages from an old system to a new system. As part of this migration I want to mark the messages as read. In order to do this I need to get the messages associated to a conversation so that I can send a 'read' receipt for each message

However I'm unable to see how I can get the messages in a conversation using the library

So far I've got :

    def mark_as_read(conversation, recipient)
      layer_client = Layer::Client.authenticate { |nonce| Layer::IdentityToken.new(recipient.id, nonce) }
        conversation2 = Layer::Conversation.find(conversation.id, layer_client)

        conversation2.messages.each do |message|
          log_event "message: #{message.inspect}"
          #message.read!
        end
    end

Any feedback on how to accomplish this? maybe the library doesn't support this feature

thanks
Ben

**Comment by benedikt** [comment]
Hi @ikbenben!

You can get the messages in a conversation by calling `conversation2.messages.all`. This will return an Object responding to `#each`. 

I'd agree that this is counter-intuitive and I'll update the gem accordingly. In the meantime you should be good by doing `conversation2.messages.all.each`

Hope this helps!

Benedikt

**Comment by ikbenben** [comment]
Thanks @benedikt 

that worked.

**Comment by benedikt** [comment]
Hi @ikbenben!

I just pushed a change to the master branch that allows to call `each` directly on the `messages` proxy.

If you have the time, I'd appreciate your feedback! :-)

Benedikt
