### ISSUE TITLE
support for new format for Application's IDs

### ISSUE THREAD

**Issue by curbsaleem** [benedikt/layer-ruby#2]
Hi

If i pass application_id in latest format ie layer:///apps/staging/XXXXXX, it gives error 'RestClient::Forbidden: 403 Forbidden'. Can you plz look at this.

Thanks

**Comment by benedikt** [comment]
Hi @curbsaleem,

thanks a lot for reporting this. I just releases v0.3.0 to RubyGems that should fix this issue. Let me know if the problem persists. 

Cheers,

Benedikt
