### ISSUE TITLE
InvalidHeader on Layer::Client.authenticate

### ISSUE THREAD

**Issue by rrodrigu3z** [benedikt/layer-ruby#23]
Hi, I'm getting a `Layer::Exceptions::InvalidHeader` Exception when calling `Layer::Client.authenticate` after upgrading to v0.7.

With v0.6 everything works OK.

Any ideas?
Thanks.

**Comment by benedikt** [comment]
Hi @rrodrigu3z,

thanks a lot for reporting this! It's indeed a bug in 0.7.0. I just pushed a fix and released 0.7.1

Cheers,

Benedikt

**Comment by benedikt** [comment]
You're able to make every request by using the client directly. Something along those lines will work in 0.6 as well:

```ruby
Layer::Resource.client.delete('/users/1/identity')
```
