### ISSUE TITLE
2.0 API

### ISSUE THREAD

**Issue by BeamerCola** [benedikt/layer-ruby#28]
Are there any plans for 2.0 support?  Or anyway to make a single 2.0 request using the library?

Thanks!

**Comment by jegodwin** [comment]
I'm wondering this as well? Just realized that this library is targeting 1.1 API.

**Comment by BeamerCola** [comment]
@jegodwin so good news is that you can.  But you'll have to parse the JSON response manually which isn't too big of a deal

```
    client = Layer::Client::Platform.new()
    response = client.post("/conversations/.../messages", {
      sender_id: "layer:///identities/...",
      parts: []
    } , { "Accept" => "application/vnd.layer+json; version=2.0" })
```

**Comment by jegodwin** [comment]
Okay, got it. Thanks @BeamerCola.
