### ISSUE TITLE
[Question]: Using this gem for Client API Proxy?

### ISSUE THREAD

**Issue by jegodwin** [benedikt/layer-ruby#29]
Does anyone know if it's possible to use this gem for making client requests via the Client API Proxy concept as mentioned in the [Layer docs](https://docs.layer.com/reference/server_api/clientapiproxy)?

**Comment by benedikt** [comment]
Hi @jegodwin!

You can do arbitrary request by using the client directly. Check out the relevant section in the readme: 
https://github.com/benedikt/layer-ruby#using-the-gem-with-multiple-applications-at-once

Using the client instance you can do HTTP requests to the API and will get back Ruby hashes. Hope this helps. :)

Cheers,

Benedikt

**Comment by jegodwin** [comment]
Okay, got it. I overlooked this part of the Readme somehow, but I think the part I'm looking for is the Client REST stuff.

More specifically, I'm wanting to create a `follow` for the `current_user` to target user. So, would I just [auth a new client instance](https://github.com/benedikt/layer-ruby#using-the-layer-client-rest-api) and then use something like ruby's `net/http` to then make REST call's using the new client session I've just created?

Thanks for the quick reply @benedikt as well as your work on this library!

**Comment by benedikt** [comment]
@jegodwin Yes, you can use the REST Client to access the Client API directly. The instances of the client support methods like `.get` and `.post` to do HTTP requests. 

You can also use the Platform Client an do requests to the client proxy endpoints on the Platform API.

**Comment by jegodwin** [comment]
Ah, okay, I see now. Thanks for clarifying that.

I seem to remember there being docs for the `Platform Client` on Layer's website at some point. Do you know if they've deprecated the Platform Client API?

**Comment by benedikt** [comment]
The Platform API was renamed to Server API. Sorry, I keep forgetting that :)

**Comment by jegodwin** [comment]
Oh okay, that makes more sense. Thanks again for your quick responses!
