### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by curbsaleem** [benedikt/layer-ruby#3]
To create message, I m using 

conversation.messages.create({sender: {user_id: current_user.id.to_s, name: current_user.id.to_s }, parts: [{ body: 'example', mime_type: 'text/plain' }]})

But getting 422 Unprocessable Entity

**Comment by benedikt** [comment]
According to the Layer documentation, you can either define `sender.user_id` or `sender.name` but not both.

For reference, please see https://developer.layer.com/docs/platform#send-a-message

**Comment by curbsaleem** [comment]
Still getting same error.
had tried with 
- conversation.messages.create({sender: {user_id: current_user.id.to_s }, parts: [{ body: 'example', mime_type: 'text/plain' }]})
and
- conversation.messages.create(sender: {user_id: current_user.id.to_s }, parts: [{ body: 'example', mime_type: 'text/plain' }])
