### ISSUE TITLE
Layer Server API

### ISSUE THREAD

**Issue by Dorian** [benedikt/layer-ruby#30]
What about supporting the Layer Server API?

https://docs.layer.com/reference/server_api/introduction

**Comment by benedikt** [comment]
Hi @Dorian,

the Platform API was renamed to Server API. `layer-ruby` supports version 1.1 of the Server API.

Hope this helps!

Benedikt

**Comment by Dorian** [comment]
@benedikt Thanks a lot! Makes sense now, maybe it could mentioned in the README
