### ISSUE TITLE
Get messages in conversation 

### ISSUE THREAD

**Issue by geoffreymm** [benedikt/layer-ruby#5]
Thank you for making this project. It saves me a lot of time. But I face myself with a problem.
I'de like to know if it there is a way to retrieve all message in a conversation. In the Layer docs they supply methods for doing this in IOS/Android. 

And according with their [API](https://developer.layer.com/docs/platform#retrieve-a-conversation): 
*If User A wants to talk to User B, they should not need to create a new Conversation every time they talk. By reusing an existing Conversation, they can access the message history and context around their previous communications.*

I have a ***Layer::Conversation*** object, but the ***.messages*** method returns a ***Layer::RelationProxy***.  There is a way of achieving this?

Thank you!

**Comment by benedikt** [comment]
Hi Geoffrey!

I'm glad this project is helpful to you! 

Unfortunately there is no way to retrieve a list is conversations nor a conversations messages via the Layer Platform API. This is most likely because of the different authentication mechanisms used in the iOS/Android clients vs the Platform.

In theory it's probably possible to implement the layer identity token authentication in this gem, which will most likely allow to interact with the Layer API as a specific user. However, this is not implemented at the moment and not even verified to work.

This is certainly a thing to explore in the future.

Bests,

Benedikt

**Comment by benedikt** [comment]
Hi @geoffreymm!

I just started experimenting with the Layer API, adding support for identity token based authentication. There's a pull request (#8) that adds support for listing conversation and messages. If you have the time, please check it out. I'd love to hear your feedback.

Cheers,

Benedikt

**Comment by geoffreymm** [comment]
Hello @benedikt,

I'm trying to integrate these and making some testes but I'm having some problems. Before I was creating a conversation (after creating the Layer::Client on an initializer of course) this way:

layer_conversation = Layer::Conversation.create({ participants: [self.id.to_s, user.id.to_s] })

On this new version, as I understand I'm suppose to create a client for each of the participants, right?
Since the "old way" the Layer::Conversation.create method is returning a:  "404 Resource Not Found" (strange no?)

I've successfully created a client (which is a Layer::Client::REST instance) for each of the users. But then I didn't understand how I should create a conversation with those two clients. You still have the create method for the conversation. 
I'm pretty sure I didn't understand something. :) 

Best regards,
Geoff

**Comment by benedikt** [comment]
Hi @geoffreymm,

by default, the resources will use the Platform API. Or to be more precise, they're using `Layer::Resource.client`. It defaults to the Platform API Client. 

You can pass a client instance to all methods of a resource. To create a new conversation as a user you could use 

```ruby
rest_client = Layer::Client.authenticate { |nonce| # Return Layer identity token here }
conversation = Layer::Conversation.create({ participants: [self.id.to_s, user.id.to_s] }, rest_client)
```

When you create or find a conversation via the rest client, you also get access to the conversation's messages:

```ruby
messages = conversation.messages.each { |m| puts m.inspect }
```

Hope this helps!

**Comment by geoffreymm** [comment]
Hi @benedikt,

Thank you for your effort on this feature I've made some tests but the:

    messages = conversation.messages.each { |m| puts m.inspect }

Keeps on returning:

    NoMethodError: undefined method `each' for #<Layer::RelationProxy:0x007f4702c299a8>
	from /app/vendor/bundle/ruby/2.2.0/gems/layer-ruby-0.5.2/lib/layer/relation_proxy.rb:33:in   `method_missing'
	from (irb):57
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'

I've created a new user and a new conversation with the rest_client token, as you showed above.
Any clue on what could be the cause of this? 

Thanks!

**Comment by benedikt** [comment]
Hi @geoffreymm, 

I'm sorry, I made a mistake in my original example. It's `conversation.messages.all.each`. I'm aware that this is unintuitive and will change it to support `conversation.messages.each` soon. 

Bests,

Benedikt

**Comment by geoffreymm** [comment]
@benedikt, that's it, I didn't figure that it was an enumerator. Thank you!
