### ISSUE TITLE
 undefined method `participants=' for #<Layer::Conversation:0x00000007e31d20>

### ISSUE THREAD

**Issue by curbsaleem** [benedikt/layer-ruby#6]
conversation.participants.class
 => Layer::Patch::Array 
2.1.5 :014 > conversation.participants = ["55804bd569702d409a4d7d00", "55a3c04069702d18cb290000"]
NoMethodError: undefined method `participants=' for #<Layer::Conversation:0x00000007e31d20>
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/layer-ruby-0.4.1/lib/layer/resource.rb:49:in `method_missing'
	from (irb):14
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/sahil/.rvm/gems/ruby-2.1.5@curb/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'

**Comment by benedikt** [comment]
Thanks for reporting this. This is actually a bug. I'll fix it as soon as I get to it :)

**Comment by curbsaleem** [comment]
Thanks for fixing this
